export interface Recipe {
    id: number,
    title: string,
    image: string,
    usedIngredientCount: number,
    missedIngredientCount: number,
    missedIngredients: [],
    usedIngredients: [],
    likes: number,
    servings: number,
    readyInMinutes: number,
    sourceName: string,
    instructions: string,
    extendedIngredients: [],
    diet: string,
    diets: string[],
    dishTypes: [],
    cuisines: [],
    summary: string,
  }