export interface Recipe {
    id: number,
    title: string,
    image: string,
    usedIngredientCount: number,
    missedIngredientCount: number,
    missedIngredients: [],
    usedIngredients: [],
    likes: number,
    servings: number,
    readyInMinutes: number,
    sourceName: string,
    instructions: string,
    extendedIngredients: [],
  }